---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-gfs-test
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-gfs-test
    volumeMounts:
    - mountPath: "/mnt"
      name: gluster-default-volume
  volumes:
  - name: gluster-default-volume
    glusterfs:
      endpoints: glusterfs-cluster
      path: "media-storage"
      readOnly: false
  restartPolicy: Always
