apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.20
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.0.21
    ports:
      - port: 1
