apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "gluster-vol0001"
spec:
  capacity:
    storage: "2Gi"
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "/mnt/brick1/vol0001"
    readOnly: false
  persistentVolumeReclaimPolicy: "Recycle"
